package models

import "time"

// ReproPlan is the machine-readable plan generated by the inference engine.
// It drives the generator and is also written as repro-plan.json in the output.
type ReproPlan struct {
	// Metadata
	GeneratedAt    time.Time `json:"generated_at"`
	ToolVersion    string    `json:"tool_version"`
	SourcePackage  string    `json:"source_package"`
	OutputDir      string    `json:"output_dir"`

	// Core decisions
	MattermostImage string `json:"mattermost_image"`
	Topology        string `json:"topology"`      // "single-node", "multi-node"
	NodeCount       int    `json:"node_count"`
	OutputFormat    string `json:"output_format"` // "docker-compose", "kubernetes"

	// Service plan
	Services ServicePlan `json:"services"`

	// Plugin plan
	Plugins []PluginRepro `json:"plugins"`

	// Approximations made during inference
	Approximations []Approximation `json:"approximations"`

	// Items that could not be recreated
	Unsupported []UnsupportedItem `json:"unsupported"`

	// Items intentionally stubbed for safety
	Stubbed []StubbedItem `json:"stubbed"`

	// Flags passed to the generator
	Flags ReproFlags `json:"flags"`

	// LicenseProvided is true when a license file was given at init time.
	// The generator will include a license bind-mount so Enterprise features
	// (LDAP sync, SAML) are active from the very first 'make run'.
	LicenseProvided bool `json:"license_provided,omitempty"`
}

// ServicePlan lists which services will be included in the compose output.
type ServicePlan struct {
	Mattermost   MattermostServicePlan `json:"mattermost"`
	Database     DatabaseServicePlan   `json:"database"`
	Search       SearchServicePlan     `json:"search"`
	Auth         AuthServicePlan       `json:"auth"`
	FileStorage  FileStorageServicePlan `json:"file_storage"`
	Email        EmailServicePlan      `json:"email"`
	Calls        CallsServicePlan      `json:"calls"`
	Proxy        ProxyServicePlan      `json:"proxy"`
	Observability ObservabilityServicePlan `json:"observability"`
	Tunnel        TunnelServicePlan        `json:"tunnel"`
}

// MattermostServicePlan describes the core Mattermost service.
type MattermostServicePlan struct {
	Image       string `json:"image"`
	Tag         string `json:"tag"`
	Replicas    int    `json:"replicas"`
	ExposedPort int    `json:"exposed_port"`
}

// DatabaseServicePlan describes the database service.
type DatabaseServicePlan struct {
	Enabled       bool   `json:"enabled"`
	Type          string `json:"type"`    // "postgres", "mysql"
	Image         string `json:"image"`
	Tag           string `json:"tag"`
	HasReplica    bool   `json:"has_replica"`
	ExposedPort   int    `json:"exposed_port"`
}

// SearchServicePlan describes the search backend service.
type SearchServicePlan struct {
	Enabled     bool   `json:"enabled"`
	Backend     string `json:"backend"` // "opensearch", "elasticsearch", "database"
	Image       string `json:"image"`
	Tag         string `json:"tag"`
	ExposedPort int    `json:"exposed_port"`
}

// AuthServicePlan describes auth backend services.
type AuthServicePlan struct {
	LDAPEnabled     bool   `json:"ldap_enabled"`
	LDAPImage       string `json:"ldap_image,omitempty"`
	KeycloakEnabled bool   `json:"keycloak_enabled"`
	KeycloakImage   string `json:"keycloak_image,omitempty"`
	// SAMLEnabled means SAML env vars are configured in docker-compose.
	// SAML requires a Mattermost Enterprise license to function; OIDC does not.
	SAMLEnabled bool `json:"saml_enabled,omitempty"`
	// GuestAccountsEnabled means MM_GUESTSETTINGS_ENABLE is set.
	// Detected from the support package or always true for enterprise edition.
	GuestAccountsEnabled bool `json:"guest_accounts_enabled,omitempty"`
}

// FileStorageServicePlan describes the file storage service.
type FileStorageServicePlan struct {
	UseMinIO    bool   `json:"use_minio"`
	Image       string `json:"image,omitempty"`
	Tag         string `json:"tag,omitempty"`
	ExposedPort int    `json:"exposed_port,omitempty"`
}

// EmailServicePlan describes the email service.
type EmailServicePlan struct {
	UseMailHog  bool   `json:"use_mailhog"`
	Image       string `json:"image,omitempty"`
	ExposedPort int    `json:"exposed_port,omitempty"`
	UIPort      int    `json:"ui_port,omitempty"`
}

// CallsServicePlan describes the calls/RTCD service.
type CallsServicePlan struct {
	UseRTCD     bool   `json:"use_rtcd"`
	Image       string `json:"image,omitempty"`
	ExposedPort int    `json:"exposed_port,omitempty"`
}

// ProxyServicePlan describes the reverse proxy service.
type ProxyServicePlan struct {
	Enabled     bool   `json:"enabled"`
	Type        string `json:"type,omitempty"` // "nginx"
	ExposedPort int    `json:"exposed_port,omitempty"`
}

// ObservabilityServicePlan describes monitoring services.
type ObservabilityServicePlan struct {
	PrometheusEnabled bool   `json:"prometheus_enabled"`
	GrafanaEnabled    bool   `json:"grafana_enabled"`
	PrometheusPort    int    `json:"prometheus_port,omitempty"`
	GrafanaPort       int    `json:"grafana_port,omitempty"`
}

// TunnelServicePlan describes ngrok tunnel configuration for mobile / remote access.
type TunnelServicePlan struct {
	NgrokEnabled bool `json:"ngrok_enabled"`
	NgrokAPIPort int  `json:"ngrok_api_port,omitempty"` // local ngrok dashboard/API (default 4040)
}

// PluginRepro describes how a plugin will be handled in the repro.
type PluginRepro struct {
	ID          string `json:"id"`
	Name        string `json:"name,omitempty"`
	Version     string `json:"version,omitempty"`
	Action      string `json:"action"` // "install", "skip", "stub", "manual"
	Reason      string `json:"reason,omitempty"`
	InstallURL  string `json:"install_url,omitempty"`
}

// Approximation describes something recreated inexactly.
type Approximation struct {
	Component   string `json:"component"`
	Description string `json:"description"`
	Reason      string `json:"reason"`
}

// UnsupportedItem describes something that cannot be recreated locally.
type UnsupportedItem struct {
	Component   string `json:"component"`
	Description string `json:"description"`
	Workaround  string `json:"workaround,omitempty"`
}

// StubbedItem describes something intentionally replaced with a safe stub.
type StubbedItem struct {
	Component   string `json:"component"`
	Reason      string `json:"reason"`
	StubType    string `json:"stub_type"` // "disabled", "local-mock", "placeholder"
}

// ReproFlags holds the CLI flags that influenced the plan.
type ReproFlags struct {
	ForceDB            string `json:"force_db,omitempty"`
	ForceSingleNode    bool   `json:"force_single_node"`
	ForceMultiNode     bool   `json:"force_multi_node"`
	WithOpenSearch     bool   `json:"with_opensearch"`
	WithElasticsearch  bool   `json:"with_elasticsearch"`
	WithLDAP           bool   `json:"with_ldap"`
	WithSAML           bool   `json:"with_saml"`
	WithAzureAD        bool   `json:"with_azure_ad,omitempty"`
	WithMinIO          bool   `json:"with_minio"`
	WithRTCD           bool   `json:"with_rtcd"`
	WithGrafana        bool   `json:"with_grafana"`
	RedactStrict       bool   `json:"redact_strict"`
	WithKubernetes     bool   `json:"with_kubernetes"`
	ForceDockerCompose bool   `json:"force_docker_compose"`
	WithNgrok          bool   `json:"with_ngrok"`
	// LicenseFile is the path to a .mattermost-license file provided at init time.
	// When set, the generator pre-loads it so Enterprise features are active from boot.
	LicenseFile string `json:"license_file,omitempty"`
}
