package generator

import (
	"fmt"
	"strings"

	"github.com/rohith0456/mattermost-support-package-repro/pkg/models"
	"github.com/rohith0456/mattermost-support-package-repro/pkg/version"
)

// generateCompose generates the docker-compose.yml for the repro project.
func (g *Generator) generateCompose() (string, error) {
	var sb strings.Builder
	p := g.plan

	sb.WriteString("# Generated by mm-repro " + version.Short() + "\n")
	sb.WriteString("# DO NOT commit this file with real secrets — see .env for configuration\n")
	sb.WriteString("# This environment is for LOCAL DEBUGGING ONLY\n\n")
	sb.WriteString("services:\n")

	// Database
	if p.Services.Database.Enabled {
		if p.Services.Database.Type == "mysql" {
			sb.WriteString(mysqlService(p.Services.Database.ExposedPort))
		} else {
			sb.WriteString(postgresService(p.Services.Database.ExposedPort))
		}
	}

	// Search
	if p.Services.Search.Enabled {
		sb.WriteString(opensearchService(p.Services.Search.ExposedPort))
	}

	// LDAP
	if p.Services.Auth.LDAPEnabled {
		sb.WriteString(ldapService())
	}

	// Keycloak
	if p.Services.Auth.KeycloakEnabled {
		sb.WriteString(keycloakService())
	}

	// MinIO
	if p.Services.FileStorage.UseMinIO {
		sb.WriteString(minioService(p.Services.FileStorage.ExposedPort))
	}

	// MailHog (always included)
	sb.WriteString(mailhogService(p.Services.Email.ExposedPort, p.Services.Email.UIPort))

	// Mattermost (single or replicas)
	image := fmt.Sprintf("%s:%s", p.MattermostImage, p.Services.Mattermost.Tag)
	siteURL := "${MM_SITE_URL:-http://localhost}"
	if p.Topology != "multi-node" {
		siteURL = "${MM_SITE_URL:-http://localhost:8065}"
	}
	if p.Topology == "multi-node" && p.NodeCount > 1 {
		for i := 0; i < p.NodeCount; i++ {
			name := fmt.Sprintf("mattermost-%d", i+1)
			port := 8065 + i
			sb.WriteString(mattermostService(name, image, port, siteURL, p))
		}
		sb.WriteString(nginxService(p.NodeCount))
	} else {
		sb.WriteString(mattermostService("mattermost", image, 8065, siteURL, p))
	}

	// RTCD
	if p.Services.Calls.UseRTCD {
		sb.WriteString(rtcdService(p.Services.Calls.ExposedPort))
	}

	// Prometheus
	if p.Services.Observability.PrometheusEnabled {
		sb.WriteString(prometheusService(p.Services.Observability.PrometheusPort))
	}

	// Grafana
	if p.Services.Observability.GrafanaEnabled {
		sb.WriteString(grafanaService(p.Services.Observability.GrafanaPort))
	}

	// ngrok tunnel (mobile / remote access)
	if p.Services.Tunnel.NgrokEnabled {
		var tunnelTarget string
		if p.Topology == "multi-node" && p.NodeCount > 1 {
			tunnelTarget = "nginx:80"
		} else {
			tunnelTarget = fmt.Sprintf("mattermost:%d", p.Services.Mattermost.ExposedPort)
		}
		sb.WriteString(ngrokService(tunnelTarget, p.Services.Tunnel.NgrokAPIPort))
	}

	// Networks and volumes
	sb.WriteString(networksAndVolumes(p))

	return g.writeFile("docker-compose.yml", sb.String())
}

func postgresService(port int) string {
	return fmt.Sprintf(`
  postgres:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${MM_DB_USER:-mmuser}
      POSTGRES_PASSWORD: ${MM_DB_PASSWORD:-mmuser_password}
      POSTGRES_DB: ${MM_DB_NAME:-mattermost}
    ports:
      - "%d:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - mm-repro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER:-mmuser}"]
      interval: 10s
      timeout: 5s
      retries: 5

`, port)
}

func mysqlService(port int) string {
	return fmt.Sprintf(`
  mysql:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MM_DB_ROOT_PASSWORD:-rootpassword}
      MYSQL_USER: ${MM_DB_USER:-mmuser}
      MYSQL_PASSWORD: ${MM_DB_PASSWORD:-mmuser_password}
      MYSQL_DATABASE: ${MM_DB_NAME:-mattermost}
    ports:
      - "%d:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - mm-repro
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$${MYSQL_ROOT_PASSWORD:-rootpassword}"]
      interval: 10s
      timeout: 5s
      retries: 5

`, port)
}

func opensearchService(port int) string {
	return fmt.Sprintf(`
  opensearch:
    image: opensearchproject/opensearch:2.11.0
    restart: unless-stopped
    environment:
      - discovery.type=single-node
      - OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m
      - DISABLE_SECURITY_PLUGIN=true
      - DISABLE_INSTALL_DEMO_CONFIG=true
    ports:
      - "%d:9200"
      - "9600:9600"
    volumes:
      - opensearch_data:/usr/share/opensearch/data
    networks:
      - mm-repro
    healthcheck:
      test: ["CMD-SHELL", "curl -s http://localhost:9200/_cluster/health | grep -q '\"status\":\"green\\|yellow\"'"]
      interval: 30s
      timeout: 10s
      retries: 5

`, port)
}

func ldapService() string {
	return `
  openldap:
    image: osixia/openldap:1.5.0
    # osixia/openldap:1.5.0 publishes native linux/arm64 — no platform override needed.
    restart: unless-stopped
    environment:
      LDAP_ORGANISATION: "Mattermost Repro Org"
      LDAP_DOMAIN: ${LDAP_DOMAIN:-repro.local}
      LDAP_ADMIN_PASSWORD: ${LDAP_ADMIN_PASSWORD:-repro_admin_password}
      LDAP_READONLY_USER: "true"
      LDAP_READONLY_USER_USERNAME: ${LDAP_BIND_USER:-readonly}
      LDAP_READONLY_USER_PASSWORD: ${LDAP_BIND_PASSWORD:-readonly_password}
    ports:
      - "389:389"
      - "636:636"
    volumes:
      - ldap_data:/var/lib/ldap
      - ldap_config:/etc/ldap/slapd.d
      - ./ldap:/ldap:ro
    networks:
      - mm-repro

  phpldapadmin:
    image: osixia/phpldapadmin:0.9.0
    # osixia/phpldapadmin:0.9.0 publishes native linux/arm64 — no platform override needed.
    restart: unless-stopped
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: openldap
      PHPLDAPADMIN_HTTPS: "false"
    ports:
      - "8089:80"
    depends_on:
      - openldap
    networks:
      - mm-repro

`
}

func keycloakService() string {
	return `
  keycloak:
    image: quay.io/keycloak/keycloak:23.0
    restart: unless-stopped
    # --import-realm loads keycloak/repro-realm.json on first start:
    # configures OIDC client (works without license) + SAML client (needs Enterprise license)
    command: start-dev --import-realm
    environment:
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN:-admin}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD:-keycloak_admin_local_repro_only}
      KC_HTTP_PORT: 8080
    ports:
      - "8080:8080"
    volumes:
      - keycloak_data:/opt/keycloak/data
      - ./keycloak:/opt/keycloak/data/import:ro
    networks:
      - mm-repro
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/health/ready || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 10

`
}

func minioService(port int) string {
	return fmt.Sprintf(`
  minio:
    image: minio/minio:latest
    restart: unless-stopped
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:-repro_minio_user}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:-repro_minio_password}
    ports:
      - "%d:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    networks:
      - mm-repro
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 10s
      retries: 3

`, port)
}

func mailhogService(smtpPort, uiPort int) string {
	return fmt.Sprintf(`
  mailpit:
    image: axllent/mailpit:latest
    restart: unless-stopped
    ports:
      - "${MAILPIT_SMTP_PORT:-%d}:1025"
      - "${MAILPIT_PORT:-%d}:8025"
    networks:
      - mm-repro

`, smtpPort, uiPort)
}

func mattermostService(name, image string, port int, siteURL string, p *models.ReproPlan) string {
	// Use the correct DB service name in depends_on
	dbServiceName := "postgres"
	if p.Services.Database.Type == "mysql" {
		dbServiceName = "mysql"
	}
	var deps strings.Builder
	deps.WriteString(fmt.Sprintf("    depends_on:\n      %s:\n        condition: service_healthy\n", dbServiceName))
	if p.Services.Search.Enabled {
		deps.WriteString("      opensearch:\n        condition: service_healthy\n")
	}
	if p.Services.FileStorage.UseMinIO {
		deps.WriteString("      minio:\n        condition: service_healthy\n")
	}
	if p.Services.Auth.KeycloakEnabled {
		deps.WriteString("      keycloak:\n        condition: service_healthy\n")
	}

	var extra strings.Builder
	// Shared file storage (required for HA / multi-node)
	if p.Services.FileStorage.UseMinIO || (p.Topology == "multi-node" && p.NodeCount > 1) {
		extra.WriteString(fmt.Sprintf(`      MM_FILESETTINGS_DRIVERNAME: amazons3
      MM_FILESETTINGS_AMAZONS3ACCESSKEYID: ${MINIO_ROOT_USER:-minioadmin}
      MM_FILESETTINGS_AMAZONS3SECRETACCESSKEY: ${MINIO_ROOT_PASSWORD:-minio_local_repro_only}
      MM_FILESETTINGS_AMAZONS3BUCKET: mattermost
      MM_FILESETTINGS_AMAZONS3ENDPOINT: minio:9000
      MM_FILESETTINGS_AMAZONS3SSL: "false"
      MM_FILESETTINGS_AMAZONS3PATHSTYLE: "true"
`))
	}
	// Cluster (HA)
	if p.Topology == "multi-node" && p.NodeCount > 1 {
		extra.WriteString(`      MM_CLUSTERSETTINGS_ENABLE: "true"
      MM_CLUSTERSETTINGS_CLUSTERNAME: repro-cluster
`)
	}
	// OpenSearch (requires Enterprise license — pre-configured, activates on license upload + restart)
	if p.Services.Search.Enabled {
		extra.WriteString(`      MM_ELASTICSEARCHSETTINGS_CONNECTIONURL: http://opensearch:9200
      MM_ELASTICSEARCHSETTINGS_ENABLEINDEXING: "true"
      MM_ELASTICSEARCHSETTINGS_ENABLESEARCHING: "true"
      MM_ELASTICSEARCHSETTINGS_ENABLEAUTOCOMPLETE: "true"
      MM_ELASTICSEARCHSETTINGS_SKIPTLSVERIFICATION: "true"
      MM_ELASTICSEARCHSETTINGS_USERNAME: ""
      MM_ELASTICSEARCHSETTINGS_PASSWORD: ""
`)
	}
	// LDAP
	if p.Services.Auth.LDAPEnabled {
		extra.WriteString(`      MM_LDAPSETTINGS_ENABLE: "true"
      MM_LDAPSETTINGS_LDAPSERVER: openldap
      MM_LDAPSETTINGS_LDAPPORT: "389"
      MM_LDAPSETTINGS_BASEDN: dc=repro,dc=local
      MM_LDAPSETTINGS_BINDUSERNAME: cn=readonly,dc=repro,dc=local
      MM_LDAPSETTINGS_BINDPASSWORD: ${LDAP_BIND_PASSWORD:-readonly_local_repro_only}
      MM_LDAPSETTINGS_USERFILTER: "(objectClass=inetOrgPerson)"
      MM_LDAPSETTINGS_USERNAMEATTRIBUTE: uid
      MM_LDAPSETTINGS_FIRSTNAMEATTRIBUTE: givenName
      MM_LDAPSETTINGS_LASTNAMEATTRIBUTE: sn
      MM_LDAPSETTINGS_EMAILATTRIBUTE: mail
      MM_LDAPSETTINGS_IDATTRIBUTE: uid
      MM_LDAPSETTINGS_LOGINIDATTRIBUTE: uid
      MM_LDAPSETTINGS_GROUPFILTER: "(objectClass=groupOfNames)"
      MM_LDAPSETTINGS_GROUPDISPLAYNAMEATTRIBUTE: cn
      MM_LDAPSETTINGS_GROUPMEMBERATTRIBUTE: member
      MM_LDAPSETTINGS_SYNCINTERVALMINUTES: "60"
`)
	}
	// OIDC via Keycloak (no license required — uses MM_GITLABSETTINGS_*)
	if p.Services.Auth.KeycloakEnabled {
		extra.WriteString(`      MM_GITLABSETTINGS_ENABLE: "true"
      MM_GITLABSETTINGS_ID: ${OIDC_CLIENT_ID:-mattermost-client}
      MM_GITLABSETTINGS_SECRET: ${OIDC_CLIENT_SECRET:-mattermost-secret-local-repro-only}
      MM_GITLABSETTINGS_AUTHENDPOINT: http://localhost:8080/realms/repro/protocol/openid-connect/auth
      MM_GITLABSETTINGS_TOKENENDPOINT: http://keycloak:8080/realms/repro/protocol/openid-connect/token
      MM_GITLABSETTINGS_USERAPIENDPOINT: http://keycloak:8080/realms/repro/protocol/openid-connect/userinfo
`)
	}
	// SAML via Keycloak (requires Enterprise license — pre-configured, activates on license upload)
	// MM_SAMLSETTINGS_IDPMETADATAURL causes Mattermost to auto-fetch the cert from Keycloak.
	// No manual cert upload in System Console is needed.
	if p.Services.Auth.SAMLEnabled {
		extra.WriteString(`      MM_SAMLSETTINGS_ENABLE: "true"
      MM_SAMLSETTINGS_VERIFY: "false"
      MM_SAMLSETTINGS_ENCRYPT: "false"
      MM_SAMLSETTINGS_IDPMETADATAURL: http://keycloak:8080/realms/repro/protocol/saml/descriptor
      MM_SAMLSETTINGS_IDPURL: http://keycloak:8080/realms/repro/protocol/saml
      MM_SAMLSETTINGS_IDPISSUERURL: http://keycloak:8080/realms/repro
      MM_SAMLSETTINGS_SERVICEPROVIDERENTIFIER: http://localhost:8065
      MM_SAMLSETTINGS_ASSERTIONCONSUMERSERVICEURL: http://localhost:8065/login/sso/saml
      MM_SAMLSETTINGS_EMAILATTRIBUTE: email
      MM_SAMLSETTINGS_USERNAMEATTRIBUTE: preferred_username
      MM_SAMLSETTINGS_FIRSTNAMEATTRIBUTE: given_name
      MM_SAMLSETTINGS_LASTNAMEATTRIBUTE: family_name
`)
	}
	// License pre-loaded (when --license flag was provided at init time)
	if p.LicenseProvided {
		extra.WriteString(`      MM_SERVICESETTINGS_LICENSEFILELOCATION: /mattermost/licenses/mattermost.mattermost-license
`)
	}

	// Extra bind-mount volumes (e.g. license file pre-load)
	var extraVolumes strings.Builder
	if p.LicenseProvided {
		extraVolumes.WriteString("      - ./licenses:/mattermost/licenses:ro\n")
	}

	listenPort := fmt.Sprintf("%d", port)

	// Build correct DB driver and datasource defaults based on the plan's DB type
	dbDriver := "postgres"
	dbDatasource := "postgres://mmuser:mmuser_password@postgres:5432/mattermost?sslmode=disable"
	if p.Services.Database.Type == "mysql" {
		dbDriver = "mysql"
		dbDatasource = "mmuser:mmuser_password@tcp(mysql:3306)/mattermost?charset=utf8mb4,utf8&readTimeout=30s&writeTimeout=30s"
	}

	return fmt.Sprintf(`
  %s:
    image: %s
    platform: linux/amd64
    restart: unless-stopped
    environment:
      MM_SQLSETTINGS_DRIVERNAME: ${MM_DB_DRIVER:-%s}
      MM_SQLSETTINGS_DATASOURCE: ${MM_DATASOURCE:-%s}
      MM_SERVICESETTINGS_SITEURL: %s
      MM_SERVICESETTINGS_LISTENADDRESS: ":%s"
      MM_EMAILSETTINGS_SMTPSERVER: mailpit
      MM_EMAILSETTINGS_SMTPPORT: "${MAILPIT_SMTP_PORT:-1025}"
      MM_EMAILSETTINGS_ENABLESMTPAUTH: "false"
      MM_LOGSETTINGS_CONSOLELEVEL: INFO
      MM_LOGSETTINGS_FILELEVEL: DEBUG
%s    ports:
      - "${MM_PORT:-%d}:%s"
    volumes:
      - %s_logs:/mattermost/logs
      - %s_config:/mattermost/config
      - %s_plugins:/mattermost/plugins
      - %s_client_plugins:/mattermost/client/plugins
%s    networks:
      - mm-repro
%s    healthcheck:
      disable: true

`, name, image, dbDriver, dbDatasource, siteURL, listenPort, extra.String(), port, listenPort, name, name, name, name, extraVolumes.String(), deps.String())
}

func nginxService(nodeCount int) string {
	var deps strings.Builder
	for i := 1; i <= nodeCount; i++ {
		deps.WriteString(fmt.Sprintf("      - mattermost-%d\n", i))
	}
	return fmt.Sprintf(`
  nginx:
    image: nginx:alpine
    restart: unless-stopped
    command: /bin/sh -c "rm -f /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/mattermost.conf:ro
    depends_on:
%s    networks:
      - mm-repro

`, deps.String())
}

func rtcdService(port int) string {
	return fmt.Sprintf(`
  rtcd:
    image: mattermost/rtcd:latest
    # mattermost/rtcd publishes native linux/arm64 — no platform override needed.
    restart: unless-stopped
    ports:
      - "%d:8045"
      - "8443:8443/udp"
    networks:
      - mm-repro

`, port)
}

func prometheusService(port int) string {
	return fmt.Sprintf(`
  prometheus:
    image: prom/prometheus:latest
    restart: unless-stopped
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - "${PROMETHEUS_PORT:-%d}:9090"
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    networks:
      - mm-repro

`, port)
}

func grafanaService(port int) string {
	return fmt.Sprintf(`
  grafana:
    image: grafana/grafana:latest
    restart: unless-stopped
    environment:
      GF_SECURITY_ADMIN_USER: ${GRAFANA_USER:-admin}
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_PASSWORD:-admin_password}
    ports:
      - "${GRAFANA_PORT:-%d}:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus
    networks:
      - mm-repro

`, port)
}

func ngrokService(target string, apiPort int) string {
	return fmt.Sprintf(`
  ngrok:
    image: ngrok/ngrok:latest
    restart: unless-stopped
    command: http %s --log=stdout
    environment:
      NGROK_AUTHTOKEN: ${NGROK_AUTHTOKEN:-}
    ports:
      - "%d:4040"
    networks:
      - mm-repro

`, target, apiPort)
}

func networksAndVolumes(p *models.ReproPlan) string {
	var mmVolumes strings.Builder
	if p.Topology == "multi-node" && p.NodeCount > 1 {
		for i := 1; i <= p.NodeCount; i++ {
			name := fmt.Sprintf("mattermost-%d", i)
			mmVolumes.WriteString(fmt.Sprintf("  %s_logs:\n  %s_config:\n  %s_plugins:\n  %s_client_plugins:\n", name, name, name, name))
		}
	} else {
		mmVolumes.WriteString("  mattermost_data:\n  mattermost_logs:\n  mattermost_config:\n  mattermost_plugins:\n  mattermost_client_plugins:\n")
	}

	return fmt.Sprintf(`
networks:
  mm-repro:
    driver: bridge

volumes:
  postgres_data:
  mysql_data:
  opensearch_data:
  ldap_data:
  ldap_config:
  keycloak_data:
  minio_data:
%s  prometheus_data:
  grafana_data:
`, mmVolumes.String())
}
