package generator

import (
	"fmt"
	"strings"

	"github.com/rohith0456/mattermost-support-package-repro/pkg/models"
)

// generateEnv generates the .env file for the repro project.
func (g *Generator) generateEnv() (string, error) {
	p := g.plan
	var sb strings.Builder

	sb.WriteString("# Generated by mm-repro\n")
	sb.WriteString("# SECURITY: This file contains LOCAL REPRO CREDENTIALS ONLY\n")
	sb.WriteString("# NEVER use real production credentials here\n")
	sb.WriteString("# NEVER commit this file to version control\n\n")

	sb.WriteString("# ============================================================\n")
	sb.WriteString("# MATTERMOST SETTINGS\n")
	sb.WriteString("# ============================================================\n")
	sb.WriteString("MM_SITE_URL=http://localhost:8065\n")
	sb.WriteString(fmt.Sprintf("MM_IMAGE=%s\n", p.MattermostImage))
	sb.WriteString(fmt.Sprintf("MM_TAG=%s\n", p.Services.Mattermost.Tag))
	sb.WriteString("\n")

	sb.WriteString("# ============================================================\n")
	sb.WriteString("# DATABASE SETTINGS (LOCAL REPRO ONLY)\n")
	sb.WriteString("# ============================================================\n")

	if p.Services.Database.Type == "mysql" {
		sb.WriteString("MM_DB_DRIVER=mysql\n")
		sb.WriteString("MM_DB_USER=mmuser\n")
		sb.WriteString("MM_DB_PASSWORD=mmuser_password_local_repro_only\n")
		sb.WriteString("MM_DB_ROOT_PASSWORD=root_password_local_repro_only\n")
		sb.WriteString("MM_DB_NAME=mattermost\n")
		sb.WriteString("MM_DATASOURCE=mmuser:mmuser_password_local_repro_only@tcp(mysql:3306)/mattermost?charset=utf8mb4,utf8&readTimeout=30s&writeTimeout=30s\n")
	} else {
		sb.WriteString("MM_DB_DRIVER=postgres\n")
		sb.WriteString("MM_DB_USER=mmuser\n")
		sb.WriteString("MM_DB_PASSWORD=mmuser_password_local_repro_only\n")
		sb.WriteString("MM_DB_NAME=mattermost\n")
		sb.WriteString("MM_DATASOURCE=postgres://mmuser:mmuser_password_local_repro_only@postgres:5432/mattermost?sslmode=disable\n")
	}
	sb.WriteString("\n")

	if p.Services.Auth.LDAPEnabled {
		sb.WriteString("# ============================================================\n")
		sb.WriteString("# LDAP SETTINGS (LOCAL STUB ONLY)\n")
		sb.WriteString("# ============================================================\n")
		sb.WriteString("LDAP_DOMAIN=repro.local\n")
		sb.WriteString("LDAP_BASE_DN=dc=repro,dc=local\n")
		sb.WriteString("LDAP_ADMIN_PASSWORD=ldap_admin_local_repro_only\n")
		sb.WriteString("LDAP_BIND_USER=readonly\n")
		sb.WriteString("LDAP_BIND_PASSWORD=readonly_local_repro_only\n")
		sb.WriteString("\n")
	}

	if p.Services.Auth.KeycloakEnabled {
		sb.WriteString("# ============================================================\n")
		sb.WriteString("# KEYCLOAK SETTINGS (LOCAL STUB ONLY)\n")
		sb.WriteString("# ============================================================\n")
		sb.WriteString("KEYCLOAK_ADMIN=admin\n")
		sb.WriteString("KEYCLOAK_ADMIN_PASSWORD=keycloak_admin_local_repro_only\n")
		sb.WriteString("\n")
	}

	if p.Services.FileStorage.UseMinIO {
		sb.WriteString("# ============================================================\n")
		sb.WriteString("# MINIO SETTINGS (LOCAL STUB ONLY)\n")
		sb.WriteString("# ============================================================\n")
		sb.WriteString("MINIO_ROOT_USER=repro_minio_user\n")
		sb.WriteString("MINIO_ROOT_PASSWORD=minio_password_local_repro_only\n")
		sb.WriteString("MINIO_BUCKET=mattermost-repro\n")
		sb.WriteString("\n")
	}

	if p.Services.Observability.GrafanaEnabled {
		sb.WriteString("# ============================================================\n")
		sb.WriteString("# GRAFANA SETTINGS\n")
		sb.WriteString("# ============================================================\n")
		sb.WriteString("GRAFANA_USER=admin\n")
		sb.WriteString("GRAFANA_PASSWORD=grafana_admin_local_repro_only\n")
		sb.WriteString("\n")
	}

	sb.WriteString("# ============================================================\n")
	sb.WriteString("# DEFAULT ADMIN CREDENTIALS (LOCAL REPRO ONLY)\n")
	sb.WriteString("# Run 'make admin' after 'make run' to create this account.\n")
	sb.WriteString("# Email/password login always works regardless of LDAP/SAML.\n")
	sb.WriteString("# ============================================================\n")
	sb.WriteString("MM_ADMIN_USERNAME=sysadmin\n")
	sb.WriteString("MM_ADMIN_EMAIL=sysadmin@repro.local\n")
	sb.WriteString("MM_ADMIN_PASSWORD=Sysadmin1!\n")
	sb.WriteString("\n")

	sb.WriteString("# ============================================================\n")
	sb.WriteString("# EMAIL SETTINGS (Mailpit local stub — captures all outgoing emails)\n")
	sb.WriteString("# ============================================================\n")
	sb.WriteString("MM_SMTP_SERVER=mailhog\n")
	sb.WriteString("MM_SMTP_PORT=1025\n")
	sb.WriteString("\n")

	if p.Services.Tunnel.NgrokEnabled {
		sb.WriteString("# ============================================================\n")
		sb.WriteString("# NGROK TUNNEL (mobile / remote access)\n")
		sb.WriteString("# ============================================================\n")
		sb.WriteString("# Set your free ngrok auth token to remove the 1-connection limit.\n")
		sb.WriteString("# Get a free token: https://dashboard.ngrok.com/get-started/your-authtoken\n")
		sb.WriteString("# Leave blank for anonymous mode (limited to 1 simultaneous tunnel).\n")
		sb.WriteString("NGROK_AUTHTOKEN=\n")
		sb.WriteString("\n")
	}

	sb.WriteString("# ============================================================\n")
	sb.WriteString("# REPRO METADATA\n")
	sb.WriteString("# ============================================================\n")
	sb.WriteString(fmt.Sprintf("REPRO_SOURCE_VERSION=%s\n", g.plan.Services.Mattermost.Tag))
	sb.WriteString(fmt.Sprintf("REPRO_TOPOLOGY=%s\n", g.plan.Topology))

	return g.writeFile(".env", sb.String())
}

// generateReproSummary generates REPRO_SUMMARY.md
func (g *Generator) generateReproSummary() (string, error) {
	p := g.plan
	var sb strings.Builder

	sb.WriteString("# Repro Environment Summary\n\n")
	sb.WriteString("> Generated by mm-repro. For LOCAL DEBUGGING ONLY.\n\n")

	sb.WriteString("## Mattermost\n\n")
	sb.WriteString(fmt.Sprintf("- **Image**: `%s:%s`\n", p.MattermostImage, p.Services.Mattermost.Tag))
	sb.WriteString(fmt.Sprintf("- **Topology**: %s\n", p.Topology))
	if p.NodeCount > 1 {
		sb.WriteString(fmt.Sprintf("- **Nodes**: %d\n", p.NodeCount))
	}
	sb.WriteString(fmt.Sprintf("- **URL**: http://localhost:%d\n", p.Services.Mattermost.ExposedPort))
	sb.WriteString("\n")

	sb.WriteString("## First Login\n\n")
	sb.WriteString("Run this **once** after `make run` to create the admin account:\n\n")
	sb.WriteString("```bash\n")
	sb.WriteString("make admin\n")
	sb.WriteString("```\n\n")
	sb.WriteString("Then open Mattermost and sign in with:\n\n")
	sb.WriteString("| Field    | Value |\n")
	sb.WriteString("|----------|-------|\n")
	sb.WriteString("| Username | `sysadmin` |\n")
	sb.WriteString("| Password | `Sysadmin1!` |\n\n")
	sb.WriteString("> **Email/password login always works** — no license or LDAP needed.\n")
	sb.WriteString("> Configure LDAP, SAML, and other services via **System Console → Authentication** after logging in.\n\n")

	sb.WriteString("## Services\n\n")
	sb.WriteString("| Service | Status | Port | Notes |\n")
	sb.WriteString("|---------|--------|------|-------|\n")
	sb.WriteString(fmt.Sprintf("| Mattermost | Enabled | %d | %s |\n", p.Services.Mattermost.ExposedPort, p.Topology))

	if p.Services.Database.Enabled {
		sb.WriteString(fmt.Sprintf("| Database (%s) | Enabled | %d | Local repro credentials |\n",
			p.Services.Database.Type, p.Services.Database.ExposedPort))
	}
	if p.Services.Search.Enabled {
		sb.WriteString(fmt.Sprintf("| OpenSearch | Enabled | %d | Approximates %s |\n",
			p.Services.Search.ExposedPort, p.Services.Search.Backend))
	}
	if p.Services.Auth.LDAPEnabled {
		sb.WriteString("| OpenLDAP | Enabled | 389 | Stub users only |\n")
	}
	if p.Services.Auth.KeycloakEnabled {
		sb.WriteString("| Keycloak | Enabled | 8080 | Approximates customer IdP |\n")
	}
	if p.Services.FileStorage.UseMinIO {
		sb.WriteString(fmt.Sprintf("| MinIO | Enabled | %d | Approximates cloud storage |\n", p.Services.FileStorage.ExposedPort))
	}
	if p.Services.Email.UseMailHog {
		sb.WriteString(fmt.Sprintf("| Mailpit (SMTP) | Enabled | %d (SMTP) / %d (UI) | Captures all emails |\n",
			p.Services.Email.ExposedPort, p.Services.Email.UIPort))
	}
	if p.Services.Observability.PrometheusEnabled {
		sb.WriteString(fmt.Sprintf("| Prometheus | Enabled | %d | Metrics collection |\n", p.Services.Observability.PrometheusPort))
	}
	if p.Services.Observability.GrafanaEnabled {
		sb.WriteString(fmt.Sprintf("| Grafana | Enabled | %d | Metrics dashboards |\n", p.Services.Observability.GrafanaPort))
	}
	if p.Services.Tunnel.NgrokEnabled {
		sb.WriteString(fmt.Sprintf("| ngrok tunnel | Enabled | %d (dashboard) | Mobile/remote access — run `make ngrok-url` |\n", p.Services.Tunnel.NgrokAPIPort))
	}
	sb.WriteString("\n")

	if p.Services.Tunnel.NgrokEnabled {
		sb.WriteString("## Mobile / Remote Access (ngrok)\n\n")
		sb.WriteString("ngrok creates a public HTTPS URL for your local Mattermost instance.\n\n")
		sb.WriteString("```bash\n")
		sb.WriteString("# Get the public ngrok URL\n")
		sb.WriteString("make ngrok-url\n\n")
		sb.WriteString("# Or open the ngrok dashboard\n")
		sb.WriteString(fmt.Sprintf("open http://localhost:%d\n", p.Services.Tunnel.NgrokAPIPort))
		sb.WriteString("```\n\n")
		sb.WriteString("> **Note:** Set `NGROK_AUTHTOKEN` in `.env` to remove the single-connection limit.\n")
		sb.WriteString("> Free token: https://dashboard.ngrok.com/get-started/your-authtoken\n\n")
	}

	sb.WriteString("## Quick Start\n\n")
	sb.WriteString("```bash\n")
	sb.WriteString("make run\n")
	sb.WriteString("# or\n")
	sb.WriteString("docker compose up -d\n")
	sb.WriteString("```\n\n")

	sb.WriteString("## Approximations Made\n\n")
	if len(p.Approximations) == 0 {
		sb.WriteString("None significant.\n\n")
	} else {
		for _, a := range p.Approximations {
			sb.WriteString(fmt.Sprintf("- **%s**: %s (%s)\n", a.Component, a.Description, a.Reason))
		}
		sb.WriteString("\n")
	}

	sb.WriteString("## Items That Could Not Be Recreated\n\n")
	if len(p.Unsupported) == 0 {
		sb.WriteString("None.\n\n")
	} else {
		for _, u := range p.Unsupported {
			sb.WriteString(fmt.Sprintf("- **%s**: %s\n", u.Component, u.Description))
			if u.Workaround != "" {
				sb.WriteString(fmt.Sprintf("  - Workaround: %s\n", u.Workaround))
			}
		}
		sb.WriteString("\n")
	}

	sb.WriteString("## Security Notes\n\n")
	sb.WriteString("- All credentials in .env are LOCAL REPRO ONLY — not from the customer environment\n")
	sb.WriteString("- See REDACTION_REPORT.md for what was redacted from the support package\n")
	sb.WriteString("- This environment MUST NOT connect to any real production systems\n")
	sb.WriteString("- Email sending is captured by Mailpit — no real emails will be sent\n")

	return g.writeFile("REPRO_SUMMARY.md", sb.String())
}

// generateRedactionReport generates REDACTION_REPORT.md
func (g *Generator) generateRedactionReport() (string, error) {
	var sb strings.Builder

	sb.WriteString("# Redaction Report\n\n")
	sb.WriteString("> This report lists categories of values that were detected and redacted.\n")
	sb.WriteString("> **Original values are never stored or shown.**\n\n")
	sb.WriteString("## Summary\n\n")
	sb.WriteString("All sensitive values from the support package config were replaced with safe placeholders.\n")
	sb.WriteString("No original credentials, secrets, or tokens were retained.\n\n")
	sb.WriteString("## What Was Redacted\n\n")
	sb.WriteString("The following categories of values are always redacted:\n\n")
	sb.WriteString("| Category | Severity | Examples of Affected Keys |\n")
	sb.WriteString("|----------|----------|---------------------------|\n")
	sb.WriteString("| Database passwords and DSNs | High | DataSource, DataSourceReplicas |\n")
	sb.WriteString("| LDAP bind credentials | High | BindPassword, LdapPassword |\n")
	sb.WriteString("| SAML private keys and certificates | High | PrivateKeyFile, IdpCertificateFile |\n")
	sb.WriteString("| OAuth client secrets | High | ClientSecret, AppSecret |\n")
	sb.WriteString("| SMTP credentials | High | SMTPPassword, SMTPUsername |\n")
	sb.WriteString("| Cloud storage keys | High | AmazonS3SecretAccessKey, AzureAccountKey |\n")
	sb.WriteString("| License file contents | High | License, LicenseFileLocation |\n")
	sb.WriteString("| Encryption keys and salts | High | AtRestEncryptKey, PublicLinkSalt |\n")
	sb.WriteString("| Webhook secrets | Medium | WebhookSecret, SigningSecret |\n")
	sb.WriteString("| Plugin secrets and API keys | Medium | api_key, access_token |\n")
	sb.WriteString("\n")
	sb.WriteString("## Safe Handling Reminder\n\n")
	sb.WriteString("- Never share support packages over unencrypted channels\n")
	sb.WriteString("- Delete extracted files when done debugging\n")
	sb.WriteString("- Never commit support package contents to version control\n")

	return g.writeFile("REDACTION_REPORT.md", sb.String())
}

// generatePluginReport generates PLUGIN_REPORT.md
func (g *Generator) generatePluginReport() (string, error) {
	var sb strings.Builder

	sb.WriteString("# Plugin Report\n\n")
	sb.WriteString("## Detected Plugins\n\n")
	sb.WriteString("| Plugin ID | Version | Enabled | Action | Reason |\n")
	sb.WriteString("|-----------|---------|---------|--------|--------|\n")

	for _, plugin := range g.plan.Plugins {
		enabled := "No"
		version := plugin.Version
		if version == "" {
			version = "unknown"
		}
		sb.WriteString(fmt.Sprintf("| `%s` | %s | %s | %s | %s |\n",
			plugin.ID, version, enabled, plugin.Action, plugin.Reason))
	}

	if len(g.plan.Plugins) == 0 {
		sb.WriteString("| No plugins detected | - | - | - | - |\n")
	}

	sb.WriteString("\n## Manual Plugin Installation\n\n")
	sb.WriteString("For plugins marked as `manual`, download the plugin from the appropriate source\n")
	sb.WriteString("and install via the Mattermost System Console > Plugin Management.\n\n")
	sb.WriteString("**Never install plugins from untrusted sources.**\n")

	return g.writeFile("PLUGIN_REPORT.md", sb.String())
}

// generateReadme generates the generated repro README.md
func (g *Generator) generateReadme() (string, error) {
	p := g.plan
	var sb strings.Builder

	sb.WriteString("# Mattermost Repro Environment\n\n")
	sb.WriteString("> Generated by [mm-repro](https://github.com/rohith0456/mattermost-support-package-repro)\n\n")
	sb.WriteString("**THIS ENVIRONMENT IS FOR LOCAL DEBUGGING ONLY.**\n\n")

	sb.WriteString("## Quick Start\n\n")
	sb.WriteString("```bash\n")
	sb.WriteString("make run    # 1. start all containers\n")
	sb.WriteString("make admin  # 2. create sysadmin account (first time only)\n")
	sb.WriteString("```\n\n")
	sb.WriteString(fmt.Sprintf("Open http://localhost:%d and sign in:\n\n", p.Services.Mattermost.ExposedPort))
	sb.WriteString("- **Username:** `sysadmin`\n")
	sb.WriteString("- **Password:** `Sysadmin1!`\n\n")
	sb.WriteString("> Email/password login always works — no license or LDAP/SAML required for first login.\n\n")

	if p.Services.Email.UseMailHog {
		sb.WriteString(fmt.Sprintf("Email (Mailpit UI): http://localhost:%d\n\n", p.Services.Email.UIPort))
	}

	sb.WriteString("## Reports\n\n")
	sb.WriteString("- [REPRO_SUMMARY.md](./REPRO_SUMMARY.md) — What was recreated and approximated\n")
	sb.WriteString("- [REDACTION_REPORT.md](./REDACTION_REPORT.md) — What was redacted for safety\n")
	sb.WriteString("- [PLUGIN_REPORT.md](./PLUGIN_REPORT.md) — Plugin handling\n\n")

	sb.WriteString("## Commands\n\n")
	sb.WriteString("| Command | Description |\n")
	sb.WriteString("|---------|-------------|\n")
	sb.WriteString("| `make run` | Start all services |\n")
	sb.WriteString("| `make stop` | Stop all services |\n")
	sb.WriteString("| `make reset` | Stop and remove all data |\n")
	sb.WriteString("| `make logs` | Follow all service logs |\n")
	sb.WriteString("| `make ps` | Show service status |\n")
	if p.Services.Tunnel.NgrokEnabled {
		sb.WriteString("| `make ngrok-url` | Print the current public ngrok URL |\n")
		sb.WriteString("| `make mobile` | Alias for `make ngrok-url` |\n")
	}
	sb.WriteString("\n")

	if p.Services.Tunnel.NgrokEnabled {
		sb.WriteString("## Mobile / Remote Access\n\n")
		sb.WriteString("ngrok is included and will create a public HTTPS URL for Mattermost.\n\n")
		sb.WriteString("1. Start the environment: `make run`\n")
		sb.WriteString("2. Get the public URL: `make ngrok-url`\n")
		sb.WriteString("3. Open the URL on your phone — no local network required\n\n")
		sb.WriteString("> Optionally set `NGROK_AUTHTOKEN` in `.env` to get a stable URL and remove\n")
		sb.WriteString("> the simultaneous connection limit. Free token: https://dashboard.ngrok.com\n\n")
	}

	sb.WriteString("## Security\n\n")
	sb.WriteString("- Credentials in `.env` are local-only and NOT from the customer\n")
	sb.WriteString("- Default admin `sysadmin` / `Sysadmin1!` — created by `make admin`, local repro only\n")
	sb.WriteString("- Mailpit captures all outbound email — nothing is sent to real recipients\n")
	if p.Services.Tunnel.NgrokEnabled {
		sb.WriteString("- ngrok makes Mattermost publicly accessible — share the URL carefully\n")
		sb.WriteString("- Stop ngrok (or `make stop`) when done to remove the public tunnel\n")
	} else {
		sb.WriteString("- Do not expose this environment on a public network\n")
	}
	sb.WriteString("- Delete this directory when finished debugging\n")

	return g.writeFile("README.md", sb.String())
}

// GetMattermostPlanProxy returns the mattermost plan for the generator's plan.
// Used internally by compose generation.
func (g *Generator) getMattermostImage() string {
	return fmt.Sprintf("%s:%s", g.plan.MattermostImage, g.plan.Services.Mattermost.Tag)
}

// Ensure models.ReproPlan satisfies the interface for compose generation.
var _ = models.ReproPlan{}
