package generator

import (
	"fmt"
	"strings"

	"github.com/rohith0456/mattermost-support-package-repro/pkg/models"
	"github.com/rohith0456/mattermost-support-package-repro/pkg/version"
)

// generateKubernetes generates all Kubernetes manifests into kubernetes/ subdirectory.
func (g *Generator) generateKubernetes() (string, error) {
	p := g.plan

	// 00 — namespace
	if _, err := g.writeFile("kubernetes/00-namespace.yaml", k8sNamespace()); err != nil {
		return "", err
	}

	// 01 — postgres
	if p.Services.Database.Enabled {
		if p.Services.Database.Type == "mysql" {
			if _, err := g.writeFile("kubernetes/01-mysql.yaml", k8sMysqlManifest()); err != nil {
				return "", err
			}
		} else {
			if _, err := g.writeFile("kubernetes/01-postgres.yaml", k8sPostgresManifest()); err != nil {
				return "", err
			}
		}
	}

	// 02 — mailhog
	if _, err := g.writeFile("kubernetes/02-mailhog.yaml", k8sMailhogManifest()); err != nil {
		return "", err
	}

	// 03 — optional services
	seq := 3
	if p.Services.Search.Enabled {
		if _, err := g.writeFile(fmt.Sprintf("kubernetes/%02d-opensearch.yaml", seq), k8sOpensearchManifest()); err != nil {
			return "", err
		}
		seq++
	}
	if p.Services.Auth.LDAPEnabled {
		if _, err := g.writeFile(fmt.Sprintf("kubernetes/%02d-openldap.yaml", seq), k8sLDAPManifest()); err != nil {
			return "", err
		}
		seq++
	}
	if p.Services.Auth.KeycloakEnabled {
		if _, err := g.writeFile(fmt.Sprintf("kubernetes/%02d-keycloak.yaml", seq), k8sKeycloakManifest()); err != nil {
			return "", err
		}
		seq++
	}
	if p.Services.FileStorage.UseMinIO {
		if _, err := g.writeFile(fmt.Sprintf("kubernetes/%02d-minio.yaml", seq), k8sMinioManifest()); err != nil {
			return "", err
		}
		seq++
	}

	// Mattermost ConfigMap + Deployment or StatefulSet
	if _, err := g.writeFile(fmt.Sprintf("kubernetes/%02d-mattermost.yaml", seq), k8sMattermostManifest(p)); err != nil {
		return "", err
	}

	// kustomization.yaml — lists all resources
	if _, err := g.writeFile("kubernetes/kustomization.yaml", k8sKustomization(p)); err != nil {
		return "", err
	}

	return "kubernetes/", nil
}

const k8sNamespace_CONST = `# Generated by mm-repro %s — LOCAL DEBUGGING ONLY
apiVersion: v1
kind: Namespace
metadata:
  name: mattermost-repro
  labels:
    app.kubernetes.io/managed-by: mm-repro
    mm-repro: "true"
`

func k8sNamespace() string {
	return fmt.Sprintf(k8sNamespace_CONST, version.Short())
}

func k8sPostgresManifest() string {
	return `apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: mattermost-repro
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: mattermost-repro
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:15-alpine
        env:
        - name: POSTGRES_USER
          value: mmuser
        - name: POSTGRES_PASSWORD
          value: mmuser_password_local_repro_only
        - name: POSTGRES_DB
          value: mattermost
        ports:
        - containerPort: 5432
        readinessProbe:
          exec:
            command: ["pg_isready", "-U", "mmuser"]
          initialDelaySeconds: 5
          periodSeconds: 5
        volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: postgres-data
        persistentVolumeClaim:
          claimName: postgres-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: mattermost-repro
spec:
  selector:
    app: postgres
  ports:
  - port: 5432
    targetPort: 5432
`
}

func k8sMysqlManifest() string {
	return `apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  namespace: mattermost-repro
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: mattermost-repro
  labels:
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:8.0
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: root_password_local_repro_only
        - name: MYSQL_USER
          value: mmuser
        - name: MYSQL_PASSWORD
          value: mmuser_password_local_repro_only
        - name: MYSQL_DATABASE
          value: mattermost
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: mysql-data
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-data
        persistentVolumeClaim:
          claimName: mysql-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: mattermost-repro
spec:
  selector:
    app: mysql
  ports:
  - port: 3306
    targetPort: 3306
`
}

func k8sMailhogManifest() string {
	return `apiVersion: apps/v1
kind: Deployment
metadata:
  name: mailhog
  namespace: mattermost-repro
  labels:
    app: mailhog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mailhog
  template:
    metadata:
      labels:
        app: mailhog
    spec:
      containers:
      - name: mailhog
        image: axllent/mailpit:latest
        ports:
        - containerPort: 1025
          name: smtp
        - containerPort: 8025
          name: ui
---
apiVersion: v1
kind: Service
metadata:
  name: mailhog
  namespace: mattermost-repro
spec:
  selector:
    app: mailhog
  type: NodePort
  ports:
  - name: smtp
    port: 1025
    targetPort: 1025
  - name: ui
    port: 8025
    targetPort: 8025
    nodePort: 30025
`
}

func k8sOpensearchManifest() string {
	return `apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: opensearch-pvc
  namespace: mattermost-repro
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: opensearch
  namespace: mattermost-repro
  labels:
    app: opensearch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: opensearch
  template:
    metadata:
      labels:
        app: opensearch
    spec:
      containers:
      - name: opensearch
        image: opensearchproject/opensearch:2.11.0
        env:
        - name: discovery.type
          value: single-node
        - name: OPENSEARCH_JAVA_OPTS
          value: "-Xms512m -Xmx512m"
        - name: DISABLE_SECURITY_PLUGIN
          value: "true"
        - name: DISABLE_INSTALL_DEMO_CONFIG
          value: "true"
        ports:
        - containerPort: 9200
        volumeMounts:
        - name: opensearch-data
          mountPath: /usr/share/opensearch/data
      volumes:
      - name: opensearch-data
        persistentVolumeClaim:
          claimName: opensearch-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: opensearch
  namespace: mattermost-repro
spec:
  selector:
    app: opensearch
  ports:
  - port: 9200
    targetPort: 9200
`
}

func k8sLDAPManifest() string {
	return `apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ldap-data-pvc
  namespace: mattermost-repro
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: openldap
  namespace: mattermost-repro
  labels:
    app: openldap
spec:
  replicas: 1
  selector:
    matchLabels:
      app: openldap
  template:
    metadata:
      labels:
        app: openldap
    spec:
      containers:
      - name: openldap
        image: osixia/openldap:1.5.0
        args: ["--copy-service"]
        env:
        - name: LDAP_ORGANISATION
          value: "Mattermost Repro Org"
        - name: LDAP_DOMAIN
          value: repro.local
        - name: LDAP_ADMIN_PASSWORD
          value: ldap_admin_local_repro_only
        - name: LDAP_READONLY_USER
          value: "true"
        - name: LDAP_READONLY_USER_USERNAME
          value: readonly
        - name: LDAP_READONLY_USER_PASSWORD
          value: readonly_local_repro_only
        ports:
        - containerPort: 389
        volumeMounts:
        - name: ldap-data
          mountPath: /var/lib/ldap
      volumes:
      - name: ldap-data
        persistentVolumeClaim:
          claimName: ldap-data-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: openldap
  namespace: mattermost-repro
spec:
  selector:
    app: openldap
  ports:
  - port: 389
    targetPort: 389
`
}

func k8sKeycloakManifest() string {
	return `apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: keycloak-pvc
  namespace: mattermost-repro
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  namespace: mattermost-repro
  labels:
    app: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
      - name: keycloak
        image: quay.io/keycloak/keycloak:23.0
        args: ["start-dev", "--import-realm"]
        env:
        - name: KEYCLOAK_ADMIN
          value: admin
        - name: KEYCLOAK_ADMIN_PASSWORD
          value: keycloak_admin_local_repro_only
        - name: KC_HTTP_PORT
          value: "8080"
        - name: KC_HOSTNAME_STRICT
          value: "false"
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: keycloak-data
          mountPath: /opt/keycloak/data
      volumes:
      - name: keycloak-data
        persistentVolumeClaim:
          claimName: keycloak-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: keycloak
  namespace: mattermost-repro
spec:
  selector:
    app: keycloak
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30080
`
}

func k8sMinioManifest() string {
	return `apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-pvc
  namespace: mattermost-repro
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio
  namespace: mattermost-repro
  labels:
    app: minio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
      - name: minio
        image: minio/minio:latest
        args: ["server", "/data", "--console-address", ":9001"]
        env:
        - name: MINIO_ROOT_USER
          value: minioadmin
        - name: MINIO_ROOT_PASSWORD
          value: minio_local_repro_only
        ports:
        - containerPort: 9000
          name: api
        - containerPort: 9001
          name: console
        volumeMounts:
        - name: minio-data
          mountPath: /data
      volumes:
      - name: minio-data
        persistentVolumeClaim:
          claimName: minio-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: minio
  namespace: mattermost-repro
spec:
  selector:
    app: minio
  type: NodePort
  ports:
  - name: api
    port: 9000
    targetPort: 9000
  - name: console
    port: 9001
    targetPort: 9001
    nodePort: 30901
`
}

func k8sMattermostManifest(p *models.ReproPlan) string {
	var sb strings.Builder

	// ConfigMap with all env vars
	sb.WriteString(k8sMattermostConfigMap(p))
	sb.WriteString("\n---\n")

	// Single-node: Deployment. Multi-node: StatefulSet
	if p.Topology == "multi-node" && p.NodeCount > 1 {
		sb.WriteString(k8sMattermostStatefulSet(p))
		sb.WriteString("\n---\n")
		sb.WriteString(k8sMattermostHeadlessService())
		sb.WriteString("\n---\n")
		sb.WriteString(k8sMattermostNodePortService(30065))
	} else {
		sb.WriteString(k8sMattermostDeployment(p))
		sb.WriteString("\n---\n")
		sb.WriteString(k8sMattermostNodePortService(30065))
	}

	return sb.String()
}

func k8sMattermostConfigMap(p *models.ReproPlan) string {
	image := fmt.Sprintf("%s:%s", p.MattermostImage, p.Services.Mattermost.Tag)
	dbDriver := "postgres"
	dbSource := "postgres://mmuser:mmuser_password_local_repro_only@postgres:5432/mattermost?sslmode=disable"
	if p.Services.Database.Type == "mysql" {
		dbDriver = "mysql"
		dbSource = "mmuser:mmuser_password_local_repro_only@tcp(mysql:3306)/mattermost?charset=utf8mb4,utf8"
	}

	var extra strings.Builder
	if p.Services.FileStorage.UseMinIO || (p.Topology == "multi-node" && p.NodeCount > 1) {
		extra.WriteString(`  MM_FILESETTINGS_DRIVERNAME: "amazons3"
  MM_FILESETTINGS_AMAZONS3ACCESSKEYID: "minioadmin"
  MM_FILESETTINGS_AMAZONS3SECRETACCESSKEY: "minio_local_repro_only"
  MM_FILESETTINGS_AMAZONS3BUCKET: "mattermost"
  MM_FILESETTINGS_AMAZONS3ENDPOINT: "minio:9000"
  MM_FILESETTINGS_AMAZONS3SSL: "false"
  MM_FILESETTINGS_AMAZONS3PATHSTYLE: "true"
`)
	}
	if p.Topology == "multi-node" && p.NodeCount > 1 {
		extra.WriteString(`  MM_CLUSTERSETTINGS_ENABLE: "true"
  MM_CLUSTERSETTINGS_CLUSTERNAME: "repro-cluster"
`)
	}
	if p.Services.Auth.LDAPEnabled {
		extra.WriteString(`  MM_LDAPSETTINGS_ENABLE: "true"
  MM_LDAPSETTINGS_LDAPSERVER: "openldap"
  MM_LDAPSETTINGS_LDAPPORT: "389"
  MM_LDAPSETTINGS_BASEDN: "dc=repro,dc=local"
  MM_LDAPSETTINGS_BINDUSERNAME: "cn=readonly,dc=repro,dc=local"
  MM_LDAPSETTINGS_BINDPASSWORD: "readonly_local_repro_only"
  MM_LDAPSETTINGS_USERFILTER: "(objectClass=inetOrgPerson)"
  MM_LDAPSETTINGS_USERNAMEATTRIBUTE: "uid"
  MM_LDAPSETTINGS_FIRSTNAMEATTRIBUTE: "givenName"
  MM_LDAPSETTINGS_LASTNAMEATTRIBUTE: "sn"
  MM_LDAPSETTINGS_EMAILATTRIBUTE: "mail"
  MM_LDAPSETTINGS_IDATTRIBUTE: "uid"
`)
	}
	if p.Services.Auth.KeycloakEnabled {
		extra.WriteString(`  MM_GITLABSETTINGS_ENABLE: "true"
  MM_GITLABSETTINGS_ID: "mattermost-client"
  MM_GITLABSETTINGS_SECRET: "mattermost-secret-local-repro-only"
  MM_GITLABSETTINGS_AUTHENDPOINT: "http://localhost:30080/realms/repro/protocol/openid-connect/auth"
  MM_GITLABSETTINGS_TOKENENDPOINT: "http://keycloak:8080/realms/repro/protocol/openid-connect/token"
  MM_GITLABSETTINGS_USERAPIENDPOINT: "http://keycloak:8080/realms/repro/protocol/openid-connect/userinfo"
`)
	}

	return fmt.Sprintf(`apiVersion: v1
kind: ConfigMap
metadata:
  name: mattermost-config
  namespace: mattermost-repro
data:
  MM_SQLSETTINGS_DRIVERNAME: %q
  MM_SQLSETTINGS_DATASOURCE: %q
  MM_SERVICESETTINGS_SITEURL: "http://localhost:30065"
  MM_SERVICESETTINGS_LISTENADDRESS: ":8065"
  MM_EMAILSETTINGS_SMTPSERVER: "mailhog"
  MM_EMAILSETTINGS_SMTPPORT: "1025"
  MM_EMAILSETTINGS_ENABLESMTPAUTH: "false"
  MM_LOGSETTINGS_CONSOLELEVEL: "INFO"
  MM_IMAGE: %q
%s`, dbDriver, dbSource, image, extra.String())
}

func k8sMattermostDeployment(p *models.ReproPlan) string {
	image := fmt.Sprintf("%s:%s", p.MattermostImage, p.Services.Mattermost.Tag)
	return fmt.Sprintf(`apiVersion: apps/v1
kind: Deployment
metadata:
  name: mattermost
  namespace: mattermost-repro
  labels:
    app: mattermost
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mattermost
  template:
    metadata:
      labels:
        app: mattermost
    spec:
      containers:
      - name: mattermost
        image: %s
        envFrom:
        - configMapRef:
            name: mattermost-config
        ports:
        - containerPort: 8065
`, image)
}

func k8sMattermostStatefulSet(p *models.ReproPlan) string {
	image := fmt.Sprintf("%s:%s", p.MattermostImage, p.Services.Mattermost.Tag)
	return fmt.Sprintf(`apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mattermost
  namespace: mattermost-repro
  labels:
    app: mattermost
spec:
  replicas: %d
  serviceName: mattermost-headless
  selector:
    matchLabels:
      app: mattermost
  template:
    metadata:
      labels:
        app: mattermost
    spec:
      containers:
      - name: mattermost
        image: %s
        envFrom:
        - configMapRef:
            name: mattermost-config
        ports:
        - containerPort: 8065
`, p.NodeCount, image)
}

func k8sMattermostHeadlessService() string {
	return `apiVersion: v1
kind: Service
metadata:
  name: mattermost-headless
  namespace: mattermost-repro
spec:
  clusterIP: None
  selector:
    app: mattermost
  ports:
  - port: 8065
    targetPort: 8065
`
}

func k8sMattermostNodePortService(nodePort int) string {
	return fmt.Sprintf(`apiVersion: v1
kind: Service
metadata:
  name: mattermost
  namespace: mattermost-repro
spec:
  selector:
    app: mattermost
  type: NodePort
  ports:
  - port: 8065
    targetPort: 8065
    nodePort: %d
`, nodePort)
}

func k8sKustomization(p *models.ReproPlan) string {
	var resources []string
	resources = append(resources, "  - 00-namespace.yaml")

	if p.Services.Database.Enabled {
		if p.Services.Database.Type == "mysql" {
			resources = append(resources, "  - 01-mysql.yaml")
		} else {
			resources = append(resources, "  - 01-postgres.yaml")
		}
	}
	resources = append(resources, "  - 02-mailhog.yaml")

	seq := 3
	if p.Services.Search.Enabled {
		resources = append(resources, fmt.Sprintf("  - %02d-opensearch.yaml", seq))
		seq++
	}
	if p.Services.Auth.LDAPEnabled {
		resources = append(resources, fmt.Sprintf("  - %02d-openldap.yaml", seq))
		seq++
	}
	if p.Services.Auth.KeycloakEnabled {
		resources = append(resources, fmt.Sprintf("  - %02d-keycloak.yaml", seq))
		seq++
	}
	if p.Services.FileStorage.UseMinIO {
		resources = append(resources, fmt.Sprintf("  - %02d-minio.yaml", seq))
		seq++
	}
	resources = append(resources, fmt.Sprintf("  - %02d-mattermost.yaml", seq))

	return fmt.Sprintf(`# Generated by mm-repro %s
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mattermost-repro
resources:
%s
`, version.Short(), strings.Join(resources, "\n"))
}
